name: updateDocs

on:
  push:
    branches:
      - develop

jobs:
  updateDocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "Rollphes"
          git config --global user.email "action"

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Run updateDoc
        run: npm run updateDoc
